Resolve Cycle cards temporarily showing old values
uoftblueprint/the-period-purse pull request #127
Opened 2022-04-09 15:40 UTC by kenneth-miura

# Description
See: https://uoftblueprint.slack.com/files/U027U9EVCCQ/F03AS36EE77/image_from_ios.mov

When user has multiple years logged and is on Period History Card (See below), and switches years, the card will retain it's old values for a few seconds before updating.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/22108651/162581049-ab49e78e-1ced-409b-9c3d-9d6446cfbbfb.png">

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings

2022-04-09 23:31 UTC, yuemily24 requested changes
Two tiny things of note. Looks good otherwise!

2022-04-09 23:31 UTC, yuemily24 commented on tpp-app/src/home/components/CycleCard.js
> +        <View style={[styles.card, styleWithTip]}>
```suggestion
        <View style={[ styles.card, !showTip && styles.noTip ]}>
```
Faster way of doing everything. You don't need line 55 `let styleWithTip = showTip ? {} : styles.noTip;` with this.

2022-04-09 23:31 UTC, yuemily24 commented on tpp-app/src/home/pages/CycleHistoryScreen.js
> +        React.useCallback(
Very tiny note, but you might as well add `useCallback` to the list of React imports so you don't have to prefix React dot.

2022-04-10 00:04 UTC, helen-li approved these changes
makes sense and looks good!

2022-04-10 15:53 UTC, yuemily24 approved these changes

2022-04-10 15:56 UTC, merged