TPP-00117
uoftblueprint/the-period-purse pull request #137
Opened 2022-04-16 03:23 UTC by helen-li

# Description

* After clicking the checkmark on the logging multiple days page, the user should then see the same dates on the main calendar page with the filter set to "Period Flow" 
* When switching from the main calendar page to logging multiple days page, the user should also see the same dates.  

Fixes #117 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-19 06:11 UTC, roylin2000 requested changes
Just one small change, otherwise it looks great and works well!

2022-04-19 06:11 UTC, roylin2000 commented on tpp-app/src/home/pages/SelectLogOptionOverlay.js
> +import { STACK_SCREENS } from '../CalendarNavigator';
We updated to CALENDAR_STACK_SCREENS for this one, so you'll have to change this for it to run.

2022-04-19 06:11 UTC, roylin2000 commented on tpp-app/src/home/pages/LogMultipleDatesScreen.js
> +        navigation.navigate(STACK_SCREENS.CALENDAR_PAGE, {
I think this should be CALENDAR_STACK_SCREENS as well.

2022-04-19 06:50 UTC, faye-tan commented
DO NOT MERGE has issues when working with https://github.com/uoftblueprint/the-period-purse/pull/142
well discuss wednesday night at coworking

2022-04-26 21:04 UTC, faye-tan commented
- when user finishes onboarding, post to asyncstorage a joinedDate of type Date
- say they join April 26 2022, today we can see back a year to April 2021
- say they've been using the app for a year and its now April 2023. They should still be able to scroll back to April 2021 which is 24 months.
- will prob need to create a helper method getMonthsDiffInclusive in services/utils/helpers

2022-04-27 21:50 UTC, roylin2000 approved these changes
Nice :D

2022-04-29 23:52 UTC, faye-tan commented on tpp-app/src/home/pages/CalendarScreen.js
> +const pastScroll = 12 + (getMonthsDiff(joinedDate))
can you move this inside CalendarScreen maybe in a useEffect()? And prefer using ```let``` instead of ```var```

2022-04-29 23:54 UTC, faye-tan commented on tpp-app/src/home/pages/LogMultipleDatesScreen.js
> +GETJoinedDate().then(res => { joinedDate = res })
same here, please move inside Calendar or LogMultipleDatesScreen and then pass joinedDate to Calendar

2022-04-30 00:22 UTC, faye-tan commented on tpp-app/src/home/pages/CalendarScreen.js
> +    const pastScroll = 12 + (getMonthsDiff(joinedDate))
yey 💃

2022-04-30 01:02 UTC, faye-tan approved these changes

2022-04-30 01:02 UTC, merged