Updated Symptom Selection onboarding page according to new design
uoftblueprint/the-period-purse pull request #140
Opened 2022-04-17 02:01 UTC by yichenesia

# Description

Updated onboarding page according to new design. This is the updated design (Figma) 
![image](https://user-images.githubusercontent.com/59180843/163697056-2c1f6d43-53e4-4167-ae69-efac10e23fa5.png)

This is what the page now looks like:

<img width="343" alt="Screen Shot 2022-04-16 at 10 00 44 PM" src="https://user-images.githubusercontent.com/59180843/163697067-78860a24-7a8a-4bde-8380-47904432b3df.png">

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-17 20:49 UTC, faye-tan requested changes
Can you add the skip button back pleaseee

2022-04-17 20:58 UTC, faye-tan commented
made some tweaks with Jing 
<img width="360" alt="Screen Shot 2022-04-17 at 4 58 17 PM" src="https://user-images.githubusercontent.com/35851484/163731783-209e6cfe-c5ce-4de0-812f-9ad666fe8b46.png">

2022-04-17 21:19 UTC, yichenesia commented
> Can you add the skip button back pleaseee

Added

2022-04-18 01:16 UTC, faye-tan approved these changes

2022-04-18 01:17 UTC, merged