Save disabled when no changes are made
uoftblueprint/the-period-purse pull request #159
Opened 2022-04-27 22:59 UTC by roylin2000

# Description

save disables when there are no changes now.

Fixes # (issue/ticket number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-28 00:45 UTC, kenneth-miura approved these changes
BET

2022-04-29 06:34 UTC, yuemily24 requested changes
One small thing!

2022-04-29 06:34 UTC, yuemily24 commented on tpp-app/src/home/pages/LogMultipleDatesScreen.js
> +            <TouchableOpacity disabled={!hasChanged} onPress={async() => {await onSubmit()}} style={{...styles.submitButton, opacity: hasChanged ? 1 : 0.5}}>
Careful of letting them press the button twice while `onSubmit` is running. It might do something funky like log the multiple dates twice (though I guess that wouldn't be a problem?). Best practice is to use a state to set submitting to true and attach `useEffect` to that state:
```javascript
const [submitting, setSubmitting] = useState(false);

useEffect(() => {
        if (!submitting) {
            return;
        }
        // do whatever
        // make sure to set submitting back to false at the end
}, [submitting])
```
 Then `onPress={setSubmitting(true)}`. This means that once submitting is `true`, clicking onPress won't send the function multiple times (because the state is already `true` from the first click) until the state is set back to `false`.

2022-04-29 18:04 UTC, roylin2000 commented on tpp-app/src/home/pages/LogMultipleDatesScreen.js
> +            <TouchableOpacity disabled={!hasChanged} onPress={async() => {await onSubmit()}} style={{...styles.submitButton, opacity: hasChanged ? 1 : 0.5}}>
that's genius! Let me know if the new version is correct.

2022-04-30 16:25 UTC, yuemily24 approved these changes
Looks fantastic!

2022-04-30 23:23 UTC, merged