TPP-00010
uoftblueprint/the-period-purse pull request #29
Opened 2021-11-19 17:45 UTC by kenneth-miura

# Description

Added and styled specified components for specified issues.

Also added Podfile.lock to .gitignore

Fixes #10 

## Type of change 

- [x] New feature (non-breaking change which adds functionality)

# Questions
1. I don't think I need to comment this code b/c it's all structural basically. Do I?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

2021-11-19 20:10 UTC, yuemily24 requested changes
Code looks clean! Just one small style change requested.
Re comments: I don't think comments are necessary here for the reason you listed.

2021-11-19 20:10 UTC, yuemily24 commented on tpp-app/src/settings/Settings.js
> +        justifyContent: 'space-between'
Try adding an attribute `alignItems` to vertically center the text and switch with each other. ([attribute description here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/#align-items))

2021-11-19 20:44 UTC, helen-li approved these changes
Super organized! All looks good other than the centering styling Emily mentioned.

2021-11-20 20:17 UTC, yuemily24 approved these changes
Looks good!

2021-11-22 19:18 UTC, merged