Feature/tpp 00046
uoftblueprint/the-period-purse pull request #61
Opened 2022-01-21 05:37 UTC by edwardhuahan

# Description

Added toggle to turn on daily notifications on 9 am.
When these notifications are clicked, it will open the calendar view.
<img width="306" alt="Screen Shot 2022-01-20 at 22 35 27" src="https://user-images.githubusercontent.com/17802344/150472021-6d1637cf-c866-4af0-a0fd-0eebe1323636.png">
<img width="328" alt="Screen Shot 2022-01-20 at 22 35 06" src="https://user-images.githubusercontent.com/17802344/150472027-b3dcc706-a4be-4985-9db5-db2306dc5fd9.png">

Fixes #46 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings

2022-01-21 20:28 UTC, kenneth-miura requested changes
Really like the comments! Helped a lot in navigating usage of a library I've never touched. I have a few comments, but they're pretty small. Great work!

2022-01-21 20:28 UTC, kenneth-miura commented on tpp-app/App.js
> +    PushNotificationIOS.addEventListener('localNotification', ((notification) => {
isn't the event listener here identical to the previously defined `onLocalNotification`? If it is you should just replace it with the function u defined earlier

2022-01-21 20:28 UTC, kenneth-miura commented on tpp-app/src/settings/Settings.js
> +    const getCorrectDate = () => {
Not sure if the comment out on the line `fireDate: getCorrectDate()` is on purpose. If it is, you may as well delete the commented-out line, as well as `getCorrectDate`.

2022-01-23 00:03 UTC, annie951977 approved these changes
The comments really help!

2022-01-28 02:19 UTC, kenneth-miura approved these changes
don't remember what my comments were but I'm assuming u resolved them lol gj

2022-01-29 23:08 UTC, merged